### ISSUE TITLE
Class name conflicts when advanced optimizations in shadow-cljs is enabled

### ISSUE THREAD

**Issue by olecve** [dhleong/spade#19]
**Description:**

When enabling advanced optimizations in shadow-cljs, different components start having the same class name, leading to style conflicts. This issue occurs with spade version 1.1.2 on a large codebase.

**Example:**

- When the first component appears in the DOM, it has the correct style.
- When the second component, which shares the same class name after advanced compilation, appears in the DOM, it replaces the styles of the first component.
- As a result, the first component's styles are completely broken.

The unreleased version 1.2.0 seems to fix the problem. I was just wondering if you have any plans to release it. Is it safe to use it?

**Comment by dhleong** [comment]
Woops, I think 1.2.0 not having a release is simply an oversight. The snapshot should be safe to use! The 2.0.0 snapshot should also be safe, and includes some nice [optimizations] (https://github.com/dhleong/spade/issues/10), but I've been too busy with work and life to test it very thoroughly. If you have time to check out that version I'd really appreciate it.

I'll make some time perhaps this evening or this weekend to bundle up a proper release for 1.2.0, at least.

**Comment by dhleong** [comment]
It looks like the code in the 1.2.0 snapshot was actually all released in 1.1.2, but I went ahead and created a proper release for 2.0.0. Please feel free to open new tickets if you encounter any other issues!
